# Generated by Django 2.0 on 2019-03-09 10:29

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20190302_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('SAR', 'SAR')], default='SAR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('SAR', 'SAR')], default='SAR', editable=False, max_length=3),
        ),
    ]
