# Generated by Django 2.0 on 2019-03-27 04:35

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20190309_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundrequest',
            name='approved_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('SAR', 'SAR')], default='SAR', editable=False, max_length=3),
        ),
    ]
