# Generated by Django 2.0 on 2019-01-11 20:22

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_auto_20190111_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceDebt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type', models.CharField(max_length=100, null=True, verbose_name='Type')),
                ('type_justification', models.TextField(blank=True, null=True, verbose_name='Type Justification')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20, null=True, verbose_name='Status')),
                ('status_comments', models.CharField(blank=True, max_length=500, null=True, verbose_name='Status Comments')),
                ('debt_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('SAR', 'SAR'), ('USD', 'USD $')], default='SAR', editable=False, max_length=3)),
                ('debt', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='SAR', max_digits=11, null=True, verbose_name='Debt Amount')),
                ('driver_government_id', models.CharField(max_length=20, null=True, verbose_name='Driver Government ID')),
                ('driver_full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Driver Full Name')),
                ('insurer_full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Driver Full Name')),
                ('driver_mobile', models.CharField(max_length=20, null=True, verbose_name='Driver Mobile')),
                ('accident_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Accident Location')),
                ('accident_date', models.DateTimeField(blank=True, null=True, verbose_name='Accident Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_insurance_debts', to='projects.Employee', verbose_name='Assignee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_debts', to='projects.Employee', verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_debts', to='projects.Employee', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Insurance Debt',
                'verbose_name_plural': 'Insurance Debts',
                'ordering': ('-updated_on', 'created_on'),
            },
        ),
        migrations.CreateModel(
            name='InsuranceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(null=True, upload_to='', verbose_name='Document Upload')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type', models.CharField(max_length=100, null=True, verbose_name='Type')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('insurance_debt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='insurancedebt.InsuranceDebt', verbose_name='Insurance Debt')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_insurance_debt_documents', to='projects.Employee', verbose_name='Updated By')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_insurance_debt_documents', to='projects.Employee', verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Insurance Document',
                'verbose_name_plural': 'Insurance Documents',
            },
        ),
    ]
