# Generated by Django 2.0 on 2019-03-02 10:24

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190223_1848'),
        ('insurancedebt', '0003_auto_20190223_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(null=True, verbose_name='End Date')),
                ('contract_soft_copy', models.FileField(blank=True, null=True, upload_to='', verbose_name='Contract Soft Copy')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Contract Details')),
                ('agreed_cut', models.DecimalField(decimal_places=2, max_digits=11, null=True, verbose_name='Agreed Cut')),
                ('insurance_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='projects.Organization', verbose_name='Insurance Company')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceSubContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_contract_soft_copy', models.FileField(blank=True, null=True, upload_to='', verbose_name='Sub-Contract Soft Copy')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Sub-Contract Details')),
                ('agreed_cut', models.DecimalField(decimal_places=2, help_text='This cut will take precedence over the parent-contract cut', max_digits=11, null=True, verbose_name='Agreed Cut')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_contracts', to='insurancedebt.InsuranceContract', verbose_name='Contract')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('SAR', 'SAR')], default='SAR', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='SAR', max_digits=11, null=True, verbose_name='Amount')),
                ('scheduled_date', models.DateField(null=True, verbose_name='Scheduled Date')),
                ('scheduled_on', models.DateTimeField(auto_now_add=True, verbose_name='Scheduled On')),
                ('received_on', models.DateTimeField(blank=True, null=True, verbose_name='Received On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
            ],
            options={
                'verbose_name_plural': 'Scheduled Payments',
                'verbose_name': 'Scheduled Payment',
            },
        ),
        migrations.AlterField(
            model_name='insurancedebt',
            name='insurer_full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Insurer Full Name'),
        ),
        migrations.AlterField(
            model_name='insurancedebt',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('IN_PROGRESS_INSTALLMENTS', 'In Progress (Installments)'), ('FINISHED', 'Finished'), ('DELAYED', 'Delayed'), ('CANCELLED_WRONG_PERSON', 'Cancelled (Wrong Person)'), ('CANCELLED_WONT_PAY', 'Cancelled (Client will NOT pay)'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='scheduledpayment',
            name='insurance_debt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_payments', to='insurancedebt.InsuranceDebt', verbose_name='Insurance Debt'),
        ),
        migrations.AddField(
            model_name='scheduledpayment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to='projects.Employee', verbose_name='Received By'),
        ),
        migrations.AddField(
            model_name='scheduledpayment',
            name='scheduled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_payments', to='projects.Employee', verbose_name='Scheduled By'),
        ),
        migrations.AddField(
            model_name='scheduledpayment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payments', to='projects.Employee', verbose_name='Updated By'),
        ),
    ]
