# Generated by Django 2.0 on 2019-03-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancedebt', '0005_auto_20190308_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurancedocument',
            old_name='uploaded_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='insurancedocument',
            old_name='uploaded_on',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='scheduledpayment',
            old_name='scheduled_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='scheduledpayment',
            old_name='scheduled_on',
            new_name='created_on',
        ),
        migrations.AlterField(
            model_name='scheduledpayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('TRANSFER_TO_GULF_DEBT', 'Bank transfer to Gulf Debt account'), ('TRANSFER_TO_COMPANY', 'Bank transfer to the insurance company account')], max_length=100, null=True, verbose_name='Payment Methods'),
        ),
    ]
