# Generated by Django 2.0 on 2019-04-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancedebt', '0008_auto_20190327_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedebt',
            name='ref_no',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Insurance Company Reference No'),
        ),
    ]
