# Generated by Django 2.2.3 on 2019-08-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancedebt', '0010_scheduledpayment_proof_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedebt',
            name='legacy_system_no',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Legacy System No'),
        ),
    ]
