# Generated by Django 2.0 on 2019-01-15 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurancedebt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancedebt',
            name='description',
        ),
        migrations.RemoveField(
            model_name='insurancedebt',
            name='title',
        ),
        migrations.AlterField(
            model_name='insurancedebt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_debts', to='projects.Employee', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='insurancedebt',
            name='type',
            field=models.CharField(choices=[('TRAFFIC', 'Traffic'), ('RETURNED', 'Returned')], default='TRAFFIC', max_length=100, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='insurancedebt',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_debts', to='projects.Employee', verbose_name='Updated By'),
        ),
    ]
