# Generated by Django 2.0 on 2019-02-23 18:48

import django.core.validators
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('insurancedebt', '0002_auto_20190115_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedebt',
            name='client_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Client Notes'),
        ),
        migrations.AlterField(
            model_name='insurancedebt',
            name='debt_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('SAR', 'SAR')], default='SAR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='insurancedebt',
            name='driver_government_id',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{9,11}$', message='You have entered an invalid Government ID')], verbose_name='Driver Government ID'),
        ),
        migrations.AlterField(
            model_name='insurancedebt',
            name='driver_mobile',
            field=models.CharField(help_text='format: 05XXXXXXXX', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^(05|٠٥)\\d{8}$', message='You have entered an invalid mobile number')], verbose_name='Driver Mobile'),
        ),
    ]
