# Generated by Django 2.0 on 2019-03-08 17:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190223_1848'),
        ('insurancedebt', '0004_auto_20190302_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecontract',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to='projects.Employee', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='insurancecontract',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurancecontract',
            name='employee_contact_details',
            field=models.TextField(blank=True, null=True, verbose_name='Employee Contact Details'),
        ),
        migrations.AddField(
            model_name='insurancecontract',
            name='employee_name',
            field=models.CharField(help_text='The insurance company employee who signed the contract from their side', max_length=200, null=True, verbose_name='Employee Details'),
        ),
        migrations.AddField(
            model_name='insurancecontract',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_contracts', to='projects.Employee', verbose_name='Signed By'),
        ),
        migrations.AddField(
            model_name='insurancecontract',
            name='signed_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Signed On'),
        ),
        migrations.AddField(
            model_name='insurancedebt',
            name='sub_contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_debts', to='insurancedebt.InsuranceSubContract', verbose_name='Sub-Contract'),
        ),
        migrations.AddField(
            model_name='insurancesubcontract',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subcontracts', to='projects.Employee', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='insurancesubcontract',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 3, 8, 17, 22, 41, 530896, tzinfo=utc), verbose_name='Created On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurancesubcontract',
            name='employee_contact_details',
            field=models.TextField(blank=True, null=True, verbose_name='Employee Contact Details'),
        ),
        migrations.AddField(
            model_name='insurancesubcontract',
            name='employee_name',
            field=models.CharField(help_text='The insurance company employee who signed the contract from their side', max_length=200, null=True, verbose_name='Employee Details'),
        ),
        migrations.AddField(
            model_name='insurancesubcontract',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_subcontracts', to='projects.Employee', verbose_name='Signed By'),
        ),
        migrations.AddField(
            model_name='insurancesubcontract',
            name='signed_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Signed On'),
        ),
        migrations.AddField(
            model_name='scheduledpayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('TRANSFER_TO_OWN', 'Bank transfer to own account'), ('TRANSFER_TO_COMPANY', 'Bank transfer to insurance company account')], max_length=100, null=True, verbose_name='Payment Methods'),
        ),
    ]
