# Generated by Django 2.0 on 2019-03-21 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurancedebt', '0006_auto_20190309_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancedocument',
            options={'ordering': ('created_on', 'type'), 'verbose_name': 'Insurance Document', 'verbose_name_plural': 'Insurance Documents'},
        ),
        migrations.AlterModelOptions(
            name='scheduledpayment',
            options={'ordering': ('scheduled_date', 'received_on'), 'verbose_name': 'Scheduled Payment', 'verbose_name_plural': 'Scheduled Payments'},
        ),
    ]
