# Generated by Django 2.0 on 2019-03-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancedebt', '0007_auto_20190321_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancecontract',
            options={'ordering': ('-signed_on', 'created_on'), 'verbose_name': 'Insurance Contract', 'verbose_name_plural': 'Insurance Contracts'},
        ),
        migrations.AlterModelOptions(
            name='insurancesubcontract',
            options={'ordering': ('-signed_on', 'created_on'), 'verbose_name': 'Insurance Sub-Contract', 'verbose_name_plural': 'Insurance Sub-Contracts'},
        ),
        migrations.AddField(
            model_name='insurancedebt',
            name='vehicle_plate_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Vehicle Plate NO'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='employee_name',
            field=models.CharField(help_text='The insurance company employee who signed the contract from their side', max_length=200, null=True, verbose_name='Employee Name'),
        ),
        migrations.AlterField(
            model_name='insurancedebt',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('IN_PROGRESS_INSTALLMENTS', 'In Progress (Installments)'), ('FINISHED', 'Finished'), ('DELAYED', 'Delayed'), ('CANCELLED_WRONG_PERSON', 'Cancelled (Wrong Person)'), ('CANCELLED_WONT_PAY', 'Cancelled (Client will NOT pay)'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='insurancesubcontract',
            name='employee_name',
            field=models.CharField(help_text='The insurance company employee who signed the contract from their side', max_length=200, null=True, verbose_name='Employee Name'),
        ),
    ]
