# Generated by Django 2.0 on 2019-02-23 18:48

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20180725_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundrequest',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('SAR', 'SAR')], default='SAR', editable=False, max_length=3),
        ),
    ]
