# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-04 17:40
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180801_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ('date',), 'verbose_name': 'Reminder', 'verbose_name_plural': 'Reminders'},
        ),
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ('date',), 'verbose_name': 'Update', 'verbose_name_plural': 'Updates'},
        ),
        migrations.AlterField(
            model_name='person',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Nationality',
        ),
    ]
