# Generated by Django 2.0 on 2019-02-23 18:48

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190111_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='monthly_salary_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('SAR', 'SAR')], default='SAR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='lookup_type',
            field=models.CharField(choices=[('ORGANIZATION_TYPE', 'Organization Type'), ('CASE_TYPE', 'Case Type'), ('CONSULTATION_TYPE', 'Consultation Type'), ('PAPERWORK_TYPE', 'Paperwork Type'), ('DOCUMENT_TYPE', 'Document Type'), ('COURT_TYPE', 'Court Type'), ('COURT_ROLE', 'Court Role'), ('INSURANCE_DOCUMENT_TYPE', 'Insurance Document Type')], db_index=True, max_length=30, null=True, verbose_name='Lookup Type'),
        ),
    ]
